# Generated by Django 6.0.4 on 2026-05-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_recipe_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_photo',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/'),
        ),
    ]
